name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Theme Deploy
      id: deploy
      uses: ./action-wordpress-theme-deploy
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: theme-zip
        path: ${{ steps.deploy.outputs.zip-path }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.deploy.outputs.zip-path }}
        token: ${{ secrets.GITHUB_TOKEN }}
